### ISSUE TITLE
the project depends on flutter_calendar ^0.0.4 which depends on date_utils ^0.0.1

### ISSUE THREAD

**Issue by luigifaticoso** [apptreesoftware/flutter_calendar#27]
I cannot make the get as it looks like date utils is incompatible, can you please fix? 

My pubspec:
```
environment:
  sdk: ">=2.0.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  date_utils: ^0.1.0
  tuple: ^1.0.1
  flutter_calendar: "^0.0.4"


```

**Comment by jmoscatiello** [comment]
Use in this order too
```
dependencies:
  flutter_calendar: ^0.0.3
  intl: ^0.15.0
  tuple: ^1.0.1
  date_utils: ^0.1.0
```
